resolver: nightly-2018-05-18

packages:
- .
- location:
    git: https://github.com/patrickt/proto3-wire.git
    commit: 7adafc6a1a5143a8f0e741a0828aff2628710384
  extra-dep: true

extra-deps:
- range-set-list-0.1.2.1
